### ISSUE TITLE
Why don't write in English?

### ISSUE THREAD

**Issue by mjablecnik** [ninefivefly/via_logger#1]
Hello, why are you not writing your README or CHANGELOG files in English?
When I want to read something about your package so I don't understand anything now..:

![image](https://user-images.githubusercontent.com/2686906/147591376-687cd23f-7c4d-4d4a-9cf9-0ab4b261d69d.png)

**Comment by ninefivefly** [comment]
hi,  thanks for your reminder

**Comment by mjablecnik** [comment]
Thanks for your change. Now it looks better :)
But do you plan also CHANGELOG.md file write in English please?
