### ISSUE TITLE
Log level priority

### ISSUE THREAD

**Issue by mjablecnik** [ninefivefly/via_logger#3]
Why you have so low log level for warning?

![image](https://user-images.githubusercontent.com/2686906/147655126-39cbb34f-0b75-4385-a78b-2e156446cd50.png)

Other loggers have normally warning priority between info and error logs..:

![image](https://user-images.githubusercontent.com/2686906/147655303-e65e6d77-f0b5-4819-b158-cb20019908bc.png)

**Comment by ninefivefly** [comment]
thanks.  Already fixed.
